### ISSUE TITLE
Paginator do nothing

### ISSUE THREAD

**Issue by ixfloma** [IDjinn/Discord.js-Collector#10]
i was working with this library, but it seems i can't navigate at all, the reaction reset is working but the content isn't moving.
my environment is
node v12.18.3
discord.js ^12.4.1
discord.js-collector ^1.5.5

**Comment by IDjinn** [comment]
Sorry for late, i will check

**Comment by IDjinn** [comment]
Fixed in version v1.6.0 (c2e643647275608a57c02d97179a5a5207d9e2f4) upgrade your version
