### ISSUE TITLE
Client Param

### ISSUE THREAD

**Issue by EwoX07** [IDjinn/Discord.js-Collector#11]
manager line :80
err: client param must be client somthing
i dont really get it, im using client extender

this.reactionRoleManager = new ReactionRoleManager(this, {
			storage: true, // Enable reaction role store in a Json file
			mongoDbLink: this.config.mongoDB // See here to see how setup mongoose: https://github.com/IDjinn/Discord.js-Collector/tree/dev/examples/reaction-role-manager/Note.md
		});

is this wrong?

**Comment by IDjinn** [comment]
Oh, its not wrong. The code does not support client extends, so it throws this errors.

Fixed in (a9b9c8ad9f871a288efac9de2d1656a1de503628), please update d.js-collector version.
