### ISSUE TITLE
messageReactionsRoles.map

### ISSUE THREAD

**Issue by EwoX07** [IDjinn/Discord.js-Collector#12]
TypeError: messageReactionsRoles.map is not a function
    at ReactionRoleManager.__onRemoveAllReaction (/rbd/pnpm-volume/f01c8349-cc29-499e-bebc-a133046860a1/node_modules/.registry.npmjs.org/discord.js-collector/1.6.1/node_modules/discord.js-collector/src/reaction-role/manager.js:677:53)

I got this new error....
also this line "manager.js:125"
btw, thanks for the fast recent update 😃

**Comment by IDjinn** [comment]
Fixed (33d81f2ca48c0201816b00ca1b4ab29702fd2848)

**Comment by EwoX07** [comment]
Thank you for the fast update m8, it works fine now.... 👍👍
btw, i was wondering if u have any discord server for even greater support on this package.

**Comment by EwoX07** [comment]
ohyeah, a couple things while im using the 1.6.4
theres a deprecation warning with monggose

(node:13206) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

**Comment by IDjinn** [comment]
Many problems, many bugs, I will probably have to redo it all over again ...

I will check it

**Comment by EwoX07** [comment]
please, take your time 👍

**Comment by IDjinn** [comment]
Fixed (3c65af80dbba4bd276e2b9f8b3472dc51897b9ff) update your version

For some reason, I'm using the remove all reactions function, instead of just deleting this reaction, sorry for the inconvenience

**Comment by IDjinn** [comment]
> btw, i was wondering if u have any discord server for even greater support on this package.

I wasn't thought that, it's good idea. I will make it soon and share in README file

**Comment by EwoX07** [comment]
reactionrole works fine now. great joooobb..👍
dont forget about the support server Djinn.
Thank you...

**Comment by EwoX07** [comment]
well.. was

check this line
manager.js : 415
if (!this.client.emojis.resolve(emoji))
                    return reject('Bad input: I canno\'t find emoji ' + role);

im not sure, but it shud be "+ emoji"
and i always getting that error after success making one. thats why i said it was working fine earlier.

**Comment by IDjinn** [comment]
It will be fixed in next version, thanks report
