### ISSUE TITLE
Reaction Collector map of undefined

### ISSUE THREAD

**Issue by EwoX07** [IDjinn/Discord.js-Collector#13]
this time reaction collector

TypeError: Cannot read property 'map' of undefined
    at /rbd/pnpm-volume/132446c5-eb2c-4523-af58-4ea57d3879ef/node_modules/.registry.npmjs.org/discord.js-collector/1.6.5/node_modules/discord.js-collector/src/collectors/reactionCollector.js:372:41

this line : reactionCollector.js:372:41

**Comment by IDjinn** [comment]
:facepalm: So much problems, soon i will need refractor all things

**Comment by IDjinn** [comment]
I guess i found the problem, after tests it will be published

**Comment by IDjinn** [comment]
Fixed in (9af9ec41ffbf992d3ac0e4ce383a157f81a680a7) 
It's already has been published, please upgrade. Thank you for report!
