### ISSUE TITLE
ERROR: Bad input

### ISSUE THREAD

**Issue by Ult1m1** [IDjinn/Discord.js-Collector#14]
(node:10192) UnhandledPromiseRejectionWarning: Bad input: I canno't find emoji 738846732514754690
(node:10192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

 NPM: "discord.js-collector": "^1.6.5",

**Comment by IDjinn** [comment]
Please upgrade your version, and check if it still occurs. If it do, Probably is custom guild emoji, but the but isn't in it guild.

**Comment by Ult1m1** [comment]
Version:     "discord.js-collector": "^1.6.6",
Emoji: https://getemoji.com/
Error:
 node:9228) UnhandledPromiseRejectionWarning: Bad input: I canno't find emoji %F0%9F%98%84
(node:9228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by IDjinn** [comment]
Fixed (b24e524299a3d7017b4c38aa27496cb849be6fc6) update your version (sorry for late)
