### ISSUE TITLE
Reaction Role STORAGE

### ISSUE THREAD

**Issue by Ult1m1** [IDjinn/Discord.js-Collector#15]
Hi, storage json probably doesn't work
(I don't think I have anything wrong there)

Otherwise it works well

**Comment by IDjinn** [comment]
Thanks for report! I will test and publish new version if it's have a problem

**Comment by IDjinn** [comment]
Problem identified, when it at storing was checking if json path exists, if json not exists never save files. When new version with fix is publish, i will tell here.

**Comment by IDjinn** [comment]
Published!
