### ISSUE TITLE
Reactions deletes

### ISSUE THREAD

**Issue by xMuffionex** [IDjinn/Discord.js-Collector#17]
Hi, i have an issue because, reaction role creates, but after reacting message, role has been given and reactions are removed (all). How to repair that?

**Comment by IDjinn** [comment]
Well, maybe is old version with this bug not already fixed... What is version of d.js-collector

**Comment by xMuffionex** [comment]
it's 1.6.6

**Comment by xMuffionex** [comment]
Updated to 1.6.7, and still bot removes all reactions

**Comment by xMuffionex** [comment]
next error: when someone has choice: yes or no with reactions, and reaction will be clicked by not the author, all reactions deletes. :(

**Comment by IDjinn** [comment]
Well i will check, sorry for problems

**Comment by xMuffionex** [comment]
reply when done, thanks

**Comment by xMuffionex** [comment]
do you need any GIF or image?

**Comment by IDjinn** [comment]
> do you need any GIF or image?

Yes, maybe it is useful to find the problem

**Comment by xMuffionex** [comment]
ok wait

**Comment by IDjinn** [comment]
Enable debug mode if is possible

**Comment by xMuffionex** [comment]
1st: https://i.imgur.com/KaTA9f1.gif
2nd: https://i.imgur.com/jDUZwCV.gif

**Comment by xMuffionex** [comment]
i can show you code  but i did like in your examples

**Comment by IDjinn** [comment]
No problem, so is internal problem, my guess is filter problem only

**Comment by xMuffionex** [comment]
Thanks for trying to fix it, when can you expect a revised version? Multiple users and servers are waiting; /

**Comment by IDjinn** [comment]
Bro, i've tested, it's working like we expect:
![test](https://user-images.githubusercontent.com/42049518/98472625-12134180-21d3-11eb-826c-e907c586df51.gif)

**Comment by IDjinn** [comment]
What method did you use?

**Comment by xMuffionex** [comment]
`case "clear":
                 botMessage = await message.channel.send({
                    embed: {
                        color: "RED",
                        description: "Are you sure you want to clear your TODO list?"
                    }
                })

                if (await ReactionCollector.yesNoQuestion({ botMessage, user: message.author })) {
                    await message.channel.send({
                        embed: {
                            color: "BLURPLE",
                            description: "Your todo list has been cleared"
                        }
                    }).then(x => {
                        client.db.delete(`todo.${message.author.id}`);
                        botMessage.delete()
                    })
                }
                else {
                    await message.channel.send({
                        embed:{
                            color: "BLURPLE",
                            description: "Okay, action cancelled!"
                        }
                    })
                    await botMessage.delete();
                }


            break`

**Comment by xMuffionex** [comment]
i used this yesOrNo, correct my code if there is mistake, what about reaction roles?

**Comment by IDjinn** [comment]
I've test with this code, has conflict with reaction role (it remove reaction) but will be fixed...

But no problem with some else user reaction triggering return

**Comment by IDjinn** [comment]
About Reaction Roles need more tests to affirm if it is not functional

**Comment by xMuffionex** [comment]
so reaction roles collides with yesNoQuestion?

**Comment by IDjinn** [comment]
Yeah, when rrManager try find rr role, if no results it was deleting reaction from user

**Comment by IDjinn** [comment]
It must delete only if really have rr, but not have role in guild or something like that...

**Comment by xMuffionex** [comment]
okay, when i can expect an update? 300 guilds wait for rr's 🤐

**Comment by IDjinn** [comment]
Great bro, published now

**Comment by IDjinn** [comment]
If something wrong please tell me

**Comment by xMuffionex** [comment]
will test, thanks

**Comment by xMuffionex** [comment]
oh god, works! THX! will reopen when i will have some questions

**Comment by IDjinn** [comment]
Thank you, sorry for this problems...
