### ISSUE TITLE
Database suggesstion 

### ISSUE THREAD

**Issue by xMuffionex** [IDjinn/Discord.js-Collector#19]
Hi! I think quick.db is great db, and should be added 👍. What do you think about time limit with message collectors? ex. 30seconds

**Comment by IDjinn** [comment]
I never used quick.db, i will learn about that, maybe it's good sugestion, or support for multi-database

> What do you think about time limit with message collectors? ex. 30seconds

I guess is good time to messages collector

**Comment by xMuffionex** [comment]
what's default? @IDjinn

**Comment by IDjinn** [comment]
30 seconds

**Comment by xMuffionex** [comment]
thanks

**Comment by xMuffionex** [comment]
but i think custom will be good

**Comment by IDjinn** [comment]
Yes you can do it, just pass collectorOptions property in any collectors, you can set other time

**Comment by IDjinn** [comment]
```js

    if (message.content.startsWith('>delete-channel')) {
        const botMessage = await message.reply('Are you sure? This action canno\'t be undo!');
        if (await ReactionCollector.yesNoQuestion({ botMessage, user: message.author, collectorOptions: { time: 10 * 60 * 1000 } })) {
            await message.channel.delete();
            await message.reply('Done!');
        }
        else {
            await message.reply('Ok, operation cancelled!');
        }
    }
```

**Comment by IDjinn** [comment]
Oh sorry, message collector is Inifity time

**Comment by xMuffionex** [comment]
thanks

**Comment by IDjinn** [comment]
Do it open, quick.db maybe is a good sugestion to do

**Comment by xMuffionex** [comment]
🙏 🙏 🙏

**Comment by IDjinn** [comment]
Moved to #25
