### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by EwoX07** [IDjinn/Discord.js-Collector#2]
why do i still have this error? unexpected token static DEFAULT_COLLECTOR_TIME = 30_000??

**Comment by IDjinn** [comment]
Resolved in #1, need publish new version with fix. Probably your nodejs version doesn't support it.

**Comment by IDjinn** [comment]
Thanks @GaringWoX for fixed, test new version

**Comment by EwoX07** [comment]
thanks for the update, but
you need to fix the npm publish

**Comment by IDjinn** [comment]
yeah, idk what happened...

**Comment by EwoX07** [comment]
its something with the authentication i guess

**Comment by tec-wizard** [comment]
Has this issue been fixed ?

**Comment by IDjinn** [comment]
> Has this issue been fixed ?
> I am getting the same error

I've fixed in github, but i had problems with npm. Today fix version is available in npm.


> its something with the authentication i guess

I think it's problem with github, i removed publishConfig and rename package to discord.js-collector, then the publish work in npm.
