### ISSUE TITLE
Database Role React

### ISSUE THREAD

**Issue by Ult1m1** [IDjinn/Discord.js-Collector#22]
The data is already being written to the database, but it will not be restored after the bot is restarted

**Comment by IDjinn** [comment]
Thanks for report, sorry for problems. I will check it. Are you using json or mongo database?

**Comment by Ult1m1** [comment]
JsonDne 9. 11. 2020 1:10 napsal uživatel IDjinn <notifications@github.com>:
Thanks for report, sorry for problems. I will check it. Are you using json or mongo database?

**Comment by Ult1m1** [comment]
I using Json.database.

**Comment by IDjinn** [comment]
Please upgrade your d.js-collector version, i've did some changes and fix that problem. If this problem keep, please re-open this issue. Thank you
