### ISSUE TITLE
Setup installation

### ISSUE THREAD

**Issue by xMuffionex** [IDjinn/Discord.js-Collector#23]
Hi, how i can setup this? https://i.imgur.com/A6lD4Qt.png because by default id don't works

**Comment by IDjinn** [comment]
It's not needed setup, by default in RR manager
> because by default id don't works
What you mean?

**Comment by xMuffionex** [comment]
i meant:

because by default **IT** don't works

**Comment by IDjinn** [comment]
🤔 Do you have guild members and presence intent, right?
https://github.com/IDjinn/Discord.js-Collector/blob/650e09b4c265852d86d936fcbfae36bb6ea60eda/src/reaction-role/manager.js#L247

It does on ready event

**Comment by IDjinn** [comment]
Enable debug, check if when you start show log someone won role while bot is offline

**Comment by xMuffionex** [comment]
ii have intents

**Comment by IDjinn** [comment]
Problem found, fixed and tested, it will be published. Sorry for late, i'm without PC.

**Comment by xMuffionex** [comment]
thx

**Comment by xMuffionex** [comment]
thanks a lot, is there anyway to create reactioncollector, which will be deleted after choosing a special reaction? Because i want to creeate a ticket system, and i want to send embed to special channel, and when message author will choose for example bread emoji, it will close a ticket, and reaction role collector? I have problem because i don't know how to sasve a reaction collector. Maybe when someone will click a reaction to close ticket, bot will be restarting, and after restart will not looking for reaction add at this message. is there any way to do it by this module? 
I'm sorry if my translation is wrong.

**Comment by IDjinn** [comment]
I thought it was possible, but with check is only possible with Reaction Menu or Paginator. Next version will be able to do it in others collectors...

Simple awnser: When you create some collector, you recieve collector param to stop it as you like.

**Comment by IDjinn** [comment]
>  I have problem because i don't know how to sasve a reaction collector

Is not there a way to do that, it's diposed when node process is shut down.

**Comment by IDjinn** [comment]
>Maybe when someone will click a reaction to close ticket, bot will be restarting, and after restart will not looking for reaction add at this message. is there any way to do it by this module?

Unfortunately i guess is no practice way, maybe make other command to delete it is better

**Comment by IDjinn** [comment]
> I thought it was possible, but with check is only possible with Reaction Menu or Paginator. Next version will be able to do it in others collectors...
> 
> Simple awnser: When you create some collector, you recieve collector param to stop it as you like.

Now you can stop all reaction collectors (exept yesNoQuestion) with param collector 

See [Break Changes](https://github.com/IDjinn/Discord.js-Collector/blob/master/BREAKING_CHANGES.md)
