### ISSUE TITLE
Paginator not working..

### ISSUE THREAD

**Issue by BIntelligent** [IDjinn/Discord.js-Collector#24]
whatever I do, I even wait after reaction but paginator is stuck at first embed that it initially sent.
![image](https://user-images.githubusercontent.com/65684589/98634233-c2ed1e00-2344-11eb-90b1-c08051d2b894.png)
look at that am I doing something wrong? those ai, levelling, general's are embeds I defined above this code...

**Comment by IDjinn** [comment]
This code looks right, what is you d.js-collector version?

**Comment by BIntelligent** [comment]
Its latest one, like the one you updated 1 day ago. (I installed  it few mins before posting this issue)

**Comment by IDjinn** [comment]
Thank you for report, I will check it, sorry for problems

**Comment by IDjinn** [comment]
I've did some tests (v.1.6.8), with multiples cases it's working brother... Check if all that pages is MessageEmbeds

**Comment by BIntelligent** [comment]
okay I'll recheck. Thanks I'll close the ticket.
