### ISSUE TITLE
[Feat]: Improve database support

### ISSUE THREAD

**Issue by IDjinn** [IDjinn/Discord.js-Collector#25]
**Is your feature request related to a problem? Please describe.**
Currently there is only thwo ways to store reaction role data: JSON and MongoDB

**Describe the solution you'd like**
Simple way to make it do with multiple database, or configurable to unsupported databases.

**Comment by xMuffionex** [comment]
I'm using rethinkdb, it saves JSON. Maybe you will add it? :D

**Comment by IDjinn** [comment]
Well, it's complicated... Much people use different databases, I don't found any way to compatibility all of them. I think I'll keep just JSON and MongoDb for now

If I fork reactions roles in different package, maybe I can do it for multiples database, like different modules or something like that... It's need thing about it.

**Comment by ririko5834** [comment]
ok, i think that mongodb is good database.

**Comment by IDjinn** [comment]
I'm thinking about SQL's databases (mainly mysql) for people who have big systems and bots who use SQL's databases. If i find how make it multiple SQL db support, it will be implemented.

**Comment by IDjinn** [comment]
Closed, with rewrite will be native.
