### ISSUE TITLE
Json database

### ISSUE THREAD

**Issue by Ult1m1** [IDjinn/Discord.js-Collector#26]
Hi, unfortunately the problem with the json database persists.
Everything is stored there, but after restarting the bot, the already set reaction roles do not work

**Comment by IDjinn** [comment]
After a lot tests i've found one bug in RR setup, please upgrade your version and test in your enviroinment... If this problem persist, please send here your code and your data json

**Comment by Ult1m1** [comment]
It already works, thank you!

And I would also like to ask, can it be done somehow (if I have reactions to colors, for example) so that he can always have only one role, if he clicks on the next one, the previous one will be deleted.

**Comment by IDjinn** [comment]
Yes, you can do it with `toggle` property

All roles what you want property `toggle` true, so when user choice other color, previous role will be taken from he.

**Comment by Ult1m1** [comment]
Ok so...Now I'm trying, and I can only choose one color, with the proviso that it can't be changed anymore
if I click on another color, it will give it to me for a while, but after a while it will take away from it. shouldn't it remove only the previous color?

**Comment by IDjinn** [comment]
:thinking: I will check bro, thx for report

**Comment by Ult1m1** [comment]
Could you give me your discord? I would describe those errors better there, I try to be brief here

At least we could discuss the mistake better

**Comment by IDjinn** [comment]
Yeah, of course, i'm creating a discord server suport too... Soon i'll share link
Djinn#8753

**Comment by Ult1m1** [comment]
Ult1m#2056 
You cannot send the request: D
