### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ririko5834** [IDjinn/Discord.js-Collector#33]
How can i remove reaction role? Can you add example code how to remove reaction role from database by message id or by channel mention?

**Comment by IDjinn** [comment]
Yeah, need make some example to remove... Currently just by their id. I will make it better

**Comment by IDjinn** [comment]
Done, update the package and check these example: https://github.com/IDjinn/Discord.js-Collector/blob/a9903c098fb35608ed21442b0df9389ec3bb40b4/examples/reaction-role-manager/basic.js#L65-L74

**Comment by ririko5834** [comment]
I am getting: ```(node:340) UnhandledPromiseRejectionWarning: Error: Bad input: removeRole(role) must be a ReactionRole Object.```

**Comment by IDjinn** [comment]
Which version?

**Comment by ririko5834** [comment]
"discord.js-collector": "^1.7.5",

**Comment by IDjinn** [comment]
Update discord.js-collector
