### ISSUE TITLE
Verify reaction role

### ISSUE THREAD

**Issue by ririko5834** [IDjinn/Discord.js-Collector#34]
**Describe the solution you'd like**
Hi, can you please add option to create verify reaction role. I mean that when user react to emoji bot will give him role and remove his reaction, role should not be removed when reaction will be removed.

This will be useful for react to get Member role embed panels.

**Comment by IDjinn** [comment]
Something like command with multiple roles in a embed, and when react give rr?

**Comment by ririko5834** [comment]
Something like this mode (Photo from Carl-Bot)
![image](https://user-images.githubusercontent.com/64729293/99871966-8c35c400-2bde-11eb-98f8-45c19b9d9fd2.png)

**Comment by ririko5834** [comment]
@IDjinn Can you send me example code how to create new types of reaction roles?

**Comment by ririko5834** [comment]
Btw i am getting warning
```
(node:148) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
```

**Comment by IDjinn** [comment]
> @IDjinn Can you send me example code how to create new types of reaction roles?

Sorry i guess i've forgot update samples... Here a short code about that:

```js
// update your import, add ReactionRoleType.
const { ReactionRoleManager, ReactionRoleType} = require('discord.js-collector');
        reactionRoleManager.createReactionRole({
            message: msg,
            roles: [role],
            emoji,
            type: ReactionRoleType.NORMAL // It's optional, normal by default
        });
```

You can just change ReactionRoleType ([Docs](https://idjinn.github.io/Discord.js-Collector/global.html#ReactionRoleType))

**Comment by ririko5834** [comment]
Ok, also how does this work?
```
// When someone removed all reactions from message
reactionRoleManager.on('allReactionsRemove', (message) => {
    console.log(`All reactions from message ${message.id} was removed, all roles was taken and reactions roles deleted.`)
});
```
I am often getting it to console.
Is this trigerred only when the message it also reaction role or on every message where reactions were removed?

**Comment by ririko5834** [comment]
It delete then reaction role from database?

**Comment by ririko5834** [comment]
@IDjinn Also please fix this warning:
```
(node:148) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
```

**Comment by IDjinn** [comment]
> Ok, also how does this work?
> 
> ```
> // When someone removed all reactions from message
> reactionRoleManager.on('allReactionsRemove', (message) => {
>     console.log(`All reactions from message ${message.id} was removed, all roles was taken and reactions roles deleted.`)
> });
> ```
> 
> I am often getting it to console.
> Is this trigerred only when the message is also reaction role or on every message where reactions were removed?

I will check if every message trigger it, maybe yes for some mistake of me. When someone delete message, system delete reactions role (or just disable it) of this message and trigger that event.

**Comment by IDjinn** [comment]
> @IDjinn Also please fix this warning:
> 
> ```
> (node:148) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
> ```

Weird that warn back, but i will check it

**Comment by IDjinn** [comment]
I've checked `allReactionsRemove` trigger, yes it does every message reactions remove all at same time, next version it will trigger only if message was with reaction role active.

Mongodb warning will be fixed as well.

**Comment by ririko5834** [comment]
ok
