### ISSUE TITLE
Unknown message !

### ISSUE THREAD

**Issue by Alone1166** [IDjinn/Discord.js-Collector#36]
Hello I want the reaction manager to get the message ID from all channels. how can I do it

const msg = await message.channel.messages.fetch(args[2] || message.id);

**Comment by Alone1166** [comment]
> Hello I want the reaction manager to get the message ID from all channels. how can I do it
> 
> const msg = await message.channel.messages.fetch(args[2] || message.id);

**Comment by Alone1166** [comment]
> Hello I want the reaction manager to get the message ID from all channels. how can I do it
> 
> const msg = await message.channel.messages.fetch(args[2] || message.id);

**Comment by IDjinn** [comment]
Well, is very unlikely do it. The bot will make multiple requests and probably will be banned or take a long time...

You really want do it?
