### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by EwoX07** [IDjinn/Discord.js-Collector#4]
can you make it possible to store it to database like mongodb or mongoose instead of json? if its already possible, please make an example on how to do it...

**Comment by IDjinn** [comment]
Yes, i've thinking about that, currently we have only local json store support, and acess roles collection, but not ohter way to store data.

I think i wil make it suppot mongodb, so then we can store in cloud server

**Comment by EwoX07** [comment]
you might want to change the "max roles to give" to "limit message reaction" it works like joint/disjoint. like 1 role can be taken in a group, or all of em. sorry for the bad english

**Comment by IDjinn** [comment]
I not understand what you mean, but I've saw one problem in reaction roles, I think is about that you're saying

When all roles is given, it is deleted. Next version will fixed this problem, role won't be deteleted, just wait for someone take off reaction and lose it...

**Comment by IDjinn** [comment]
Database support will be optional mongoose dependency, if you wish, you can install it and store data in mongo db.

If enabled mongodb storage,the roles will not stored in json file

**Comment by IDjinn** [comment]
Tomorrow I will test next version and publish it

**Comment by IDjinn** [comment]
It was published, update your version and check if it's working.

**Comment by EwoX07** [comment]
> I not understand what you mean, but I've saw one problem in reaction roles, I think is about that you're saying
> 
> When all roles is given, it is deleted. Next version will fixed this problem, role won't be deteleted, just wait for someone take off reaction and lose it...

i mean, it shud not "max roles to be given". if i set the max setting to 1, it'll never give anyone the roles anymore. it shud be limitting a person reaction to the message, like if theres 3 reaction, ppl can only react on two reaction which will give em 2 roles only in a message with 3 reaction and 3 roles.

**Comment by EwoX07** [comment]
thx for the update anyways, such a great support 😎

**Comment by IDjinn** [comment]
Thanks, i did my best since i wasn't home. For something what you need just talk! 😄
