### ISSUE TITLE
Animated Emoji's isn't working in reaction role

### ISSUE THREAD

**Issue by DynamoYT** [IDjinn/Discord.js-Collector#5]
I'm getting error
```

**Comment by DynamoYT** [comment]
node:29324) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
emoji_id: Value "731452197384093726>" is not snowflake.
    at RequestHandler.execute (C:\Users\verma\Desktop\h\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by IDjinn** [comment]
Please share your code with me, I think you were wrong to type
` Invalid Form Body emoji_id: Value "731452197384093726>"`
