### ISSUE TITLE
Problem installing the npm package.

### ISSUE THREAD

**Issue by ProgramFreakHD** [IDjinn/Discord.js-Collector#52]
**Is your feature request related to a problem? Please describe.**
Problem installing npm package, when I install the package by using ```npm i discord.js-collector``` I get this error [Error Message](https://i.imgur.com/q83f7gl.png).

**Describe the solution you'd like**
I would like to install the Discord.js-Collector package and use it.

**Describe alternatives you've considered**
I tried to install the package by using ```npm i discord.js-collector@1.7.8``` &  ```npm i discord.js-collector@~1.7.8``` to reveal no luck either.

**Comment by IDjinn** [comment]
I will check it, but reading the error i guess it's problem with djs and their dependencies.

**Comment by ProgramFreakHD** [comment]
I'll let's you know if it worked, my luck is shit today my server died and I have to fix it first, thanks anyway for your respond.

**Comment by IDjinn** [comment]
Closed for inactivity, if the problem persists, please open this issue
