### ISSUE TITLE
Make the bot remove it's reaction when a reaction role is deleted.

### ISSUE THREAD

**Issue by FC5570** [IDjinn/Discord.js-Collector#53]
The title is self explanatory, whenever a reaction role is deleted, make the bot remove the reaction from the message which had the reaction role.

**Comment by IDjinn** [comment]
🤔 May will have some option in manager constructor to do that in next version

**Comment by IDjinn** [comment]
Progress status: done in (32c128a74cc7648be9bc5d5f6c897a2a2ba9b765), after more tests done will be published in npm

**Comment by IDjinn** [comment]
Published in npm, upgrade your version
