### ISSUE TITLE
[Feat]: Adding quick.db db option

### ISSUE THREAD

**Issue by sahhas16** [IDjinn/Discord.js-Collector#58]
**This isn't releated to any problem tho it will be helpful!**
A lot of people new to discord.js and coding and even to this package might need to use easier db's like quick.db than mongo cause sometimes mongo is hard to setup [for beginners]
**Create a example for using quick.db**
Create a example for using the package with quick.db in the examples folder , this will defo increase interest in the package and help people who just started coding!

**None**
None

**Additional context**
No additional context 😅

**Comment by IDjinn** [comment]
Yes, quick.db is first option, but still have problems #25 Maybe in next version (I need learn it) will be available

**Comment by sahhas16** [comment]
yes , but I think , I can help you with quick.db, let me see what i can do 😄

**Comment by IDjinn** [comment]
Closed, in new version must be native

**Comment by sahhas16** [comment]
what?
