### ISSUE TITLE
[Feat]: Custom action for "Reaction" Roles

### ISSUE THREAD

**Issue by stijnb1234** [IDjinn/Discord.js-Collector#60]
**Is your feature request related to a problem? Please describe.**
No, it's just a new feature.

**Describe the solution you'd like**
Currently, you have to specify the roles you want to add/remove. It would be great if you are able to specify custom actions based on the reaction, instead of a role. So an event called reactionRoleAdd without the role parameter, but with an emoji parameter, so that you can take action based on the emoji.

**Describe alternatives you've considered**
Nvt

**Additional context**
Nvt

**Comment by IDjinn** [comment]
🤔 you mean a kind reaction collector, but working all time?

**Comment by stijnb1234** [comment]
> 🤔 you mean a kind reaction collector, but working all time?

Yes

**Comment by IDjinn** [comment]
i've thinking about that, it's need to improve performance. With that we can use jus 1 event listener for all collectors, instead one each collector.

**Comment by stijnb1234** [comment]
Nice. I would like to use this for simple reaction events. So that it's easy to add reactions to a message, and handle my own functions when a user clicks on the reaction.

**Comment by ririko5834** [comment]
Good idea

**Comment by IDjinn** [comment]
I didn't know any best way to do this as you want, 'cause... Well it's basically d.js event `messageReactionAdd`... 🤔

**Comment by stijnb1234** [comment]
```js
const reactionRoleManager = new ReactionRoleManager(client, {
    storage: true, // Enable reaction role store in a Json file
    path: __dirname + '/roles.json', // Where will save the roles if store is enabled
    mongoDbLink: 'url mongoose link' // See here to see how setup mongoose: https://github.com/IDjinn/Discord.js-Collector/blob/master/examples/reaction-role-manager/Note.md
});

reactionRoleManager.on('reactionCustomAdd', (member, reaction) => {
    console.log(member.displayName + ' clicked on the reaction' + reaction.name)
});

client.on("ready", () => {
    //Check if the message exists, if not, create it. After that, add the reaction roles.
    reactionRoleManager.createReactionRole({
        name: "mycustomreaction"
        message: msg,
        emoji,
        type: 1
    });
});
```

Something like this?

**Comment by IDjinn** [comment]
Well, it's really d.js event... But i will make something like that, like collectors infinite for verification for e.g.

**Comment by IDjinn** [comment]
Closed, after new version is done maybe i reopen that.
