### ISSUE TITLE
[Bug]: Showing wrong emojis on reactionCollector.

### ISSUE THREAD

**Issue by xlnd47** [IDjinn/Discord.js-Collector#61]
**Describe the bug**
When trying ReactionCollection.question() from [example ](https://github.com/IDjinn/Discord.js-Collector/blob/master/examples/reaction-collector/question.js) I found a bug. Doesn't use the custom emojis added into the ReactionCollector.question .

**Please insert here your code if possible**
```js
const BaseCommand = require('../../utils/structures/BaseCommand');
const { MessageEmbed } = require('discord.js');
const { MessageCollector, ReactionCollector  } = require("discord.js-collector");


module.exports = class BotsCommand extends BaseCommand {
  constructor() {
    super('bots', 'Bot', []);
  }

  async run(bot, message, args) {
    const botMessage = await message.reply('Curse or Pray?');
    ReactionCollector.question({
      botMessage,
      user: message.author,
      reactions: {
          '👍': async (reaction) => await message.react(reaction.emoji.name), // Your custom function here.
          '👎': async (reaction) => await message.react(reaction.emoji.name),
          '🕒': async (reaction) => await message.react(reaction.emoji.name)
      }
    });

  }
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/26673889/103115652-c7a33280-4663-11eb-83f1-13998e1b36b4.png)

**Desktop (please complete the following information):**
 - Discord.js Version: 12.4.1
 - Discord.js-collector Version: 1.8.4
 - Operating system: Windows 10 Pro 20H2
 - What priority this should have? Please describe: Low

- [x] I've tested in last discord.js-collector version

**Comment by IDjinn** [comment]
Thank you, I will chet it

**Comment by IDjinn** [comment]
Sorry for late update, but now it's fixed. Please upgrade your version.

**Comment by xlnd47** [comment]
Nice, thanks for the quick update!
