### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ririko5834** [IDjinn/Discord.js-Collector#62]
I want to make staff application bot for my server. 
Can you please send me example code how to make it using this package?
I want to have my questions in array (like this `let questions = ["question1", "question2"]`) and I want that bot will ask first question, wait for response, then ask another question from array. I want to have response timeout for user 5 mins (that when user didnt responded to question within 5min promt will be ended and message will be sent). Answers should be returned in array, then i will make embed from it and send it to specifed channel.

**Comment by IDjinn** [comment]
There is a example:

```js

        const { MessageCollector } = require("discord.js-collector");

        const questions = ["q1", "q2"];
        const answers = [];
        for (const question of questions) {
            const botMessage = await message.channel.send(question);
            const msg = await MessageCollector.asyncQuestion({
                botMessage,
                user: message.author.id,
                collectorOptions: { time: 5 * 60 * 1000, max: 1 }
            });
            answers.push(msg.content);
        }
        return answers;
        ```
