### ISSUE TITLE
(node:624) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

### ISSUE THREAD

**Issue by ElmerAintGood** [IDjinn/Discord.js-Collector#69]
i was gonna test out this package to use, but it keeps saying this error whenever i try to use it, and doesnt give me role when i react. (node:624) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated.

**Comment by IDjinn** [comment]
It already does it...
https://github.com/IDjinn/Discord.js-Collector/blob/e28b8867e3f04a0a5c09cec7d6dada4c37815642/src/reaction-role/manager.js#L307-L311
