### ISSUE TITLE
Not working at all.

### ISSUE THREAD

**Issue by BIntelligent** [IDjinn/Discord.js-Collector#9]
I made a new bot with code only you provided and 
![Screenshot - 10_8_2020 , 12_34_37 PM](https://user-images.githubusercontent.com/65684589/95428802-f3672400-0962-11eb-8b29-56a48509ef39.png)

**Comment by IDjinn** [comment]
This method was deprecated, use createReactionRole instead

**Comment by GalackQSM** [comment]
même erreur

**Comment by IDjinn** [comment]
I will check what's going on 🤔

**Comment by GalackQSM** [comment]
dite moi quand c'est bon ;)

**Comment by IDjinn** [comment]
I've found the problem. `addRole(options)` was removed from lib, but it's keep in exmaple. Now it's fixed (968fc193fb3e6977873a24bf72f2d8764aac23a5)
